like/urls.py
from django.urls import path


from .views import *

app_name = 'like'

urlpatterns = [
    path('', index, name='index'),
    path('like_post/', likePost, name='like_post')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('like.urls'))
]

like/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    liked = models.ManyToManyField(
        User, default=None, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author')

    def __str__(self) -> str:
        return str(self.title)

    @property
    def totalLike(self):
        return self.liked.all().count()


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,
                             default='Like', max_length=10)

    def __str__(self) -> str:
        return str(self.post)

like/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse

# Create your views here.
from .models import *


def index(request):
    posts = Post.objects.order_by('-created')[:10]
    user = request.user
    context = {
        'posts': posts,
        'user': user,
    }
    return render(request, 'like/index.html', context)


def likePost(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post-id')
        post = Post.objects.get(id=post_id)

        if user in post.liked.all():
            post.liked.remove(user)
        else:
            post.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, post=post)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

        data = {
            'value': like.value,
            'likes': post.totalLike,
        }

        return JsonResponse(data, safe=False)

    return JsonResponse('likePost', safe=False)

like/templates/like/index.html
{% extends "main_layout.html" %}
{% load static %}

{% block title %}
    Like
{% endblock title %}

{% block content %}
    <h3>Post</h3>
    {% for post in posts %}
        <div class="card">
            <div class="card-body">
                <h4>{{post.title}}</h4>
                <p>{{post.body}}</p>
            </div>
        </div>
        <form action="{% url 'like:like_post' %}" method="POST" class="mt-3 like-post" id="{{post.id}}">
            {% csrf_token %}
            <input type="hidden" name="post-id" value="{{post.id}}">
            
            <button class="btn like-btn{{post.id}}" type="submit">
                {% if user not in post.liked.all %}
                Like
                {% else %}
                Unlike
                {% endif %}
            </button>
        </form>
        <div class="row">
            <div class="col">
                <strong class="like-value{{post.id}}">
                    {% with total=post.liked.all.count %}
                        {{ total }}
                    {% endwith %}
                </strong>
                {% with total=post.liked.all.count %}
                    like{{ total|pluralize }}
                {% endwith %}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

{% block end_script %}
<script src="{% static 'js/like.js' %}" type="text/javascript"></script>
{% endblock end_script %}

templates/main_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
          
        {% endblock title %}
    </title>

    {% include "snippets/style.html" %}

    {% block early_script %}
      
    {% endblock early_script %}
</head>
<body>
    
    <div class="container">
    {% block content %}
      
    {% endblock content %}
    </div>

    {% include "snippets/script.html" %}

    {% block end_script %}
      
    {% endblock end_script %}
</body>
</html>

templates/snippets/script.html
{% load static %}

<script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>

templates/snippets/style.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">